#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api:
  path: /api
  controller: App\Controller\AuthController::api
  methods: [POST|GET]

login_check:
  path:     /login_check
  methods:  [POST]

app.swagger_ui:
  path: /doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }